name: ruby
on:
  push:

jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: gem install nokogiri --no-document

      - name: Run Ruby tests
        run: ruby tests/balance_test.rb